[target.aarch64-linux-android]
 ar = "/Users/shuais/out/NDK/arm64/bin/aarch64-linux-android-ar"
 linker = "/Users/shuais/out/NDK/arm64/bin/aarch64-linux-android-clang"
[target.armv7-linux-androideabi]
  ar = "/Users/shuais/out/NDK/arm/bin/arm-linux-androideabi-ar"
  linker = "/Users/shuais/out/NDK/arm/bin/arm-linux-androideabi-clang"
[target.i686-linux-android]
  ar = "/Users/shuais/out/NDK/x86/bin/i686-linux-android-ar"
  linker = "/Users/shuais/out/NDK/x86/bin/i686-linux-android-clang"


